In [47]:
import numpy as np
from numpy import linalg as LA

#входные данные
A = np.array([[1, -1, 30, -16], 
              [1, 6, 8, -3], 
              [1, 1, 1, -1], 
              [0, 5, 7, -2]])

#находим U, S, V
U, S, V = LA.svd(A, full_matrices=False)
#print(U.shape, S.shape, V.shape)
#print(U) print(S) print(V)

#находим усеченные U, S, V для r
r = 2
Ur = U[:, :r]
Sr = S[:r]
Vr = V[:r, :]
print(Ur)
Srd=np.diag(Sr)
print(Srd)
print(Vr)

#собственные числа слева A*A.T
#print(LA.eigvals(A.dot(A.T)))

#собственные числа справа A*A.T
#print(LA.eigvals(A.T.dot(A)))

#восстанавливаем матрицу А и сравниваем с исходной
UrSrd=Ur.dot(Srd)
Ar=UrSrd.dot(Vr)

print(Ar)
print(A)

[[-0.94679109  0.32184005]
 [-0.24481854 -0.71798575]
 [-0.03969757 -0.11083598]
 [-0.20512097 -0.60714976]]
[[35.83924895  0.        ]
 [ 0.          7.98252206]]
[[-0.03435639 -0.04429285 -0.8883508   0.45573088]
 [-0.06351147 -0.97417073 -0.05631915 -0.20925066]]
[[  1.00262368  -0.99977987  29.99908028 -16.00157361]
 [  0.66545245   5.97193128   8.11727394  -2.799348  ]
 [  0.10507171   0.92491503   1.31371256  -0.46324776]
 [  0.56038074   5.04701625   6.80356138  -2.33610025]]
[[  1  -1  30 -16]
 [  1   6   8  -3]
 [  1   1   1  -1]
 [  0   5   7  -2]]
